-- Supabase Seed Data for Clínica de Estética
-- Insert initial Treatments
INSERT INTO public.treatments (id, name, description, category, popular, highlight, duration, price, image, benefits) VALUES
('botox', 'Botox (Toxina Botulínica)', 'Suavize linhas de expressão e previna o envelhecimento precoce com resultados naturais.', 'facial', true, false, '30 min', 'R$ 980,00', 'https://lh3.googleusercontent.com/aida-public/AB6AXuBN6mAS0GY7g5i227Y8iLm2CJAn7Oh8ao6UhyS24sCRGq53bfGp5_Tl8nw2-UXzsJAJ-Nvd6DAqOXv-k5XoH--VZiM5-Zw9aJGe3l91WzWNqj6xiQsn7kTwqS-FBAfuJdxAZ3uJWc4WLHpwGg69EK1eFmcxIiYzCVEUMLLAp0REXWeJBu86qUvNgvRM-cItt5CGdiuDu-OT2T0ayAJD4U0rOptsxZYG3_I5cbUjUxNy8ap0diflMj5s7Q', ARRAY['Prevenção de rugas profundas', 'Elevação das sobrancelhas', 'Resultados naturais e elegantes']),
('limpeza-de-pele', 'Limpeza de Pele Profunda', 'Remoção de impurezas, cravos e renovação celular para uma pele viçosa e saudável.', 'facial', false, false, '60 min', 'R$ 150,00', 'https://lh3.googleusercontent.com/aida-public/AB6AXuBhlHxlbE90w6BcgjA9jPP1jp2OwR7nextm00QGKo9dHMwvoS6c546ObG4PTx3TbwzhpAmqNEHbu5GcK4yxAygg8m-l8ggV7e3T7QC1Q7DqOg8Nq0XYc3XZ0JwbLMPJq3WDA8KIbW7PsxPQM2VEfUdJ8vtmlPzDmAC5njOqxFr0oirppIAxgoxaIU-lJJ-p4Sn2iX8YMkPzpMl5kzV4e94RTywEWiIszWl5STSolCjzYAwXkLvigUK36Q', ARRAY['Controle de oleosidade', 'Desobstrução de poros', 'Extração profissional sem cicatrizes']),
('ultraformer-iii', 'Ultraformer III', 'Lifting facial sem cortes através de ultrassom microfocado para flacidez e contorno.', 'facial', false, false, '45 min', 'R$ 1.800,00', 'https://lh3.googleusercontent.com/aida-public/AB6AXuD_IjB2cUoPht2sl_DZYyB3vJMjlSCe1_wZjmTD5JGAQNWKA_UOeXHWzgSD7Dbnq0HAO0jg8lmZLuyVakuMYOgb28GZ3xdcRprPjj0zj7Ny7PrOzr_KTYyfkWEgPBNIVTMJM7x4xHmPpTKyYvriNGMk2_P4MSZtahQ5av3dvE5Ytv1zXrV4RPqzmbvhgQTtIlTaZmes1SarXwlIGe9K8B0erqu0ekfS6e6788Jj1w34XHPQ14uNhiyrVA', ARRAY['Estímulo de colágeno intenso', 'Efeito bichectomia-like', 'Melhora imediata e contínua']),
('lipo-enzimatica', 'Lipo Enzimática', 'Combata a gordura localizada de forma minimamente invasiva com aplicação direcionada de enzimas redutoras.', 'corporal', false, true, '30 min', 'R$ 350,00 por sessão', 'https://lh3.googleusercontent.com/aida-public/AB6AXuDdALPIr_mYm1IpZ7vCO9l1Ig0tpHhxV3V-0HKjFn9mecvFZyxFIyylHXBV5Cz0TWimfvBzTHZ0nmbiEBz5JkCoWJbCOkasFfIIzfs_541sZQS0n7fk332hqrrCuGN0lJei0Iwcvd2sWoE8c1vOUEAAJ655BarsW0f5bgvY0okJpDpZJ0MUvVr8rCak0xGAH6SF1ciLhUB1P9MeTgbUQPRQbVAEqtDa6c_6Y2OGYVmXLqBBfjkNEIrQRw', ARRAY['Redução de medidas', 'Foco em gordura localizada', 'Processo rápido e focado']),
('criofrequencia', 'Criofrequência', 'Terapia que combina frio e calor para combater flacidez e celulite.', 'corporal', false, false, '40 min', 'R$ 290,00 por sessão', 'https://lh3.googleusercontent.com/aida-public/AB6AXuCO93tAHf875s1-UCImJPNISVNu6pSRixbQieMiOPdiQfB-fsvVEPv9ONbzuFM6b5aZl2chHy5b5SRB2xZuyle3-LEA_nc_qf2z5I9kyNpjIDX4zlghYGpAJgtlyhUt8SCoPiBu-TEFS7QtVt3gnJvypQi3h2uC0thBGZ-z2YSDMwEKRiwQiovy-Dtic-ZEZQHrtgk65LI_mnNqWZIqbeyPcOxE4zx9yjN7vCiZrFkU9ALVkELxnVPKeA', ARRAY['Tratamento de flacidez', 'Redução de celulite', 'Contração imediata de fibras de colágeno']),
('velashape', 'Velashape', 'Tecnologia ELOS para contorno corporal e redução da aparência de celulite.', 'corporal', false, false, '45 min', 'R$ 320,00 por sessão', 'https://lh3.googleusercontent.com/aida-public/AB6AXuCWvYCUfN8KRHHq1aHXZR4f0k_tMS-o0RBcufjxhi6kZDtOxLYQyGavdI6v-LulH6W8BiDu7HHToQOuh0VXzWgATFaRw3Aj2lVeLvbL81ROVkzy9T7vfDBCxpDzfaKwSIZa8IQ5cDc8swJ5TlkOePpyzk335MDGWGlFE38PE7stUnpx6UffXyUD-3phkq9Gu0Ww6JgYonm9vxZTYlPsLY5Fimp5QojPyMpLEWXDPY4h3BtEy8jTk_uNMA', ARRAY['Contorno corporal', 'Estímulo à circulação', 'Ação profunda no tecido adiposo']),
('massagem-relaxante', 'Massagem Relaxante', 'Um momento sagrado de desconexão. Alivia tensões musculares, reduz o estresse e promove o equilíbrio mental através de técnicas envolventes.', 'bem-estar', false, false, '60 min', 'R$ 180,00', 'https://lh3.googleusercontent.com/aida-public/AB6AXuCw7_SmkXnHIyc7_F-FA3t1X11EpJQvqaPjDwTQ2aLtOhUMXdgqLDWEVpBpKqmPwqQyLf4Sr2L-SmLYDEgazbCxczQFwvWSBOlQbJ7UlCCbmvJedznz56_yhA8y6SFokyeTBwnF2T0DWkxYY3_eJqWQ5KCpJv1YCpKLDpGS-oGGSgZjjqxXoykJlKcyqH89ZYyErMB_T5GMdu8r-fBazcVmoDtEDs4LTN44ug-4_iloD2jeSkxIx1-N1g', ARRAY['Alívio do estresse', 'Equilíbrio mental', 'Desconexão do cotidiano e relaxamento profundo']),
('massagem-modeladora', 'Massagem Modeladora', 'Manobras intensas e rápidas que auxiliam na redução de medidas, melhora da circulação e modelagem da silhueta corporal.', 'bem-estar', false, false, '50 min', 'R$ 220,00', 'https://lh3.googleusercontent.com/aida-public/AB6AXuDPZVdmtLQKU7wed_9R2C8ZeMLgoVs6ysuvkOpSNl7ylCw3K08TQudzAzu_lbIc6MDWX1vvD6SdfSaYIf48hIeFtoDlGU-xr6EBOWRi0q3CgYCWfDecwzj9hqBXQF7VATW7vhiGcYx2bGw9ENYGfm_fOu3qQz1T3ZFNZVQFlkFAARyIKdrLGB8vGRGfePRyxh7KaX5xAiO0pNPIdqKydueS84aRTH8aaDrPw3P2qnbXeSXTbSO89icK0w', ARRAY['Melhora de circulação', 'Modelagem da silhueta', 'Auxílio na eliminação de toxinas'])
ON CONFLICT (id) DO NOTHING;

-- Insert initial Promotions
INSERT INTO public.promotions (id, badge, title, subtitle, discount, original_price, promo_price, coupon_code, expires_in_days, treatment_id, active) VALUES
('promo-1', 'OFERTA DESTAQUE DO MÊS', 'Combo Brilho & Rejuvenescimento', 'Botox 3 áreas + Peeling de Diamante para uma pele renovada e radiante.', '30% OFF', 'R$ 1.200', 'R$ 840', 'ESTETICA30', 5, 'botox', true),
('promo-2', 'ESTÍMULO DE COLÁGENO', 'Protocolo Contorno & Firmeza', 'Bioestimulador de Colágeno com Drenagem Facial de cortesia.', 'R$ 350 OFF', 'R$ 1.950', 'R$ 1.600', 'FIRM2026', 8, 'ultraformer-iii', true),
('promo-3', 'RENOVAÇÃO FACIAL EXPRESS', 'Limpeza de Pele HD + LED', 'Limpeza profunda com hidratação e fototerapia anti-inflamatória.', '25% OFF', 'R$ 280', 'R$ 210', 'PELEPERFEITA', 3, 'limpeza-de-pele', true)
ON CONFLICT (id) DO NOTHING;

-- Insert initial Testimonials
INSERT INTO public.testimonials (id, name, role, text, stars, avatar_bg) VALUES
('1', 'Marina Santos', 'Cliente há 3 anos', 'Simplesmente a melhor experiência que já tive em uma clínica. O atendimento é impecável e os resultados do Botox foram super naturais, exatamente como eu queria.', 5, 'bg-secondary-fixed-dim text-secondary'),
('2', 'Fernanda Lima', 'Cliente há 1 ano', 'Fiz o pacote de corporal (Velashape) e estou encantada. A equipe é muito capacitada e o ambiente é muito relaxante. Vale cada centavo!', 5, 'bg-primary-fixed text-primary'),
('3', 'Camila Oliveira', 'Cliente Nova', 'A limpeza de pele mais completa que já fiz. Saí com a pele iluminada e me sentindo super cuidada. Recomendo de olhos fechados!', 5, 'bg-tertiary-fixed text-tertiary')
ON CONFLICT (id) DO NOTHING;

-- Insert initial FAQs
INSERT INTO public.faqs (id, question, answer) VALUES
('faq-1', 'Os procedimentos são doloridos?', 'A maioria dos nossos procedimentos são minimamente invasivos e causam apenas um leve desconforto. Utilizamos anestésicos tópicos de alta qualidade sempre que necessário para garantir sua total comodidade.'),
('faq-2', 'Quanto tempo dura o efeito do Botox?', 'Em média, os resultados da toxina botulínica duram entre 4 a 6 meses, variando de acordo com o organismo de cada paciente e seus hábitos de vida.'),
('faq-3', 'Como funciona o agendamento?', 'Você pode agendar sua avaliação clicando no botão "Agendar Consulta" em nosso menu ou através do nosso WhatsApp. Realizamos uma consulta prévia para entender suas necessidades e indicar o melhor protocolo.')
ON CONFLICT (id) DO NOTHING;

-- Insert initial Blog Posts
INSERT INTO public.blog_posts (id, title, slug, category, author, date, read_time, featured, image, excerpt, content) VALUES
('post-1', 'Bioestimuladores de Colágeno: O Segredo do Rejuvenescimento Natural', 'bioestimuladores-de-colageno-guia', 'Tratamentos Faciais', 'Dra. Camila Vasconcelos', '24 de Julho, 2026', '5 min de leitura', true, 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?auto=format&fit=crop&w=800&q=80', 'Descubra como os bioestimuladores acionam a produção natural de colágeno pelo próprio organismo, devolvendo firmeza e viço sem alterar seus traços.', 'Os bioestimuladores de colágeno revolucionaram a dermatologia estética avançada ao oferecer um rejuvenescimento gradual, seguro e extremamente natural. Diferente dos preenchedores tradicionais que apenas conferem volume imediato, substâncias como o ácido poli-L-láctico e a hidroxiapatita de cálcio estimulam as células do próprio corpo a produzirem novas fibras de colágeno.'),
('post-2', 'Cuidados Essenciais com a Pele Pós-Procedimento Estético', 'cuidados-pos-procedimento-estetico', 'Skincare & Dicas', 'Dr. Lucas Ribeiro', '18 de Julho, 2026', '4 min de leitura', true, 'https://images.unsplash.com/photo-1512290900676-26c2a48f4134?auto=format&fit=crop&w=800&q=80', 'Saiba o que fazer e o que evitar logo após sessões de Botox, Peeling ou Ultraformer para maximizar seus resultados com segurança.', 'Realizar um procedimento estético é apenas metade da jornada para alcançar a pele dos seus sonhos. Os cuidados domiciliares pós-procedimento desempenham um papel crucial na otimização dos resultados e na prevenção de reações indesejadas.'),
('post-3', 'Ultraformer III vs. Preenchimento: Qual o Melhor para Flacidez?', 'ultraformer-vs-preenchimento', 'Tecnologias Avançadas', 'Dra. Camila Vasconcelos', '10 de Julho, 2026', '6 min de leitura', false, 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=800&q=80', 'Entenda a diferença entre ultrassom microfocado e ácido hialurônico para escolher a abordagem perfeita para o seu rosto.', 'Uma das dúvidas mais frequentes na clínica é se o melhor caminho para tratar a queda do contorno facial é o Ultraformer III ou o preenchimento com ácido hialurônico. A resposta curta é: eles possuem indicações distintas e frequentemente se complementam!')
ON CONFLICT (id) DO NOTHING;
